[build]
  publish = "dist/public"
  command = "npm ci && npm run build"
  
[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=8192"
  GENERATE_SOURCEMAP = "false"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200